global using Authentication.API.Models;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Behaviors;
global using Carter;
global using FluentValidation;
global using Mapster;
global using Marten;
global using MediatR;
